version: "3.9"
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    working_dir: /opt/project
    volumes:
      - .:/opt/project
    ports:
      - 3000:3000
 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_ENDPOINT=http://localhost:3000/v1
    image: frontend
    ports:
       - "8080:80"
