name: Go lint
on:
  push:
    paths:
      - backend/**
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.19"
        id: go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 3m --verbose 
          working-directory: backend

      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-flags: "-l -d"

      - name: Test
        run: cd backend && go test -v ./...

